JuliaStats/PDMats.jl

.travis.yml
README.md
src/PDMats.jl
src/addition.jl
src/chol.jl
src/pdsparsemat.jl
src/utils.jl
test/addition.jl
test/pdmtypes.jl

A type and the required functions for sparse covariance matrices as mention in #23. However, I need some help with two points:
-  It passes the `test_pdmat` test, however, not the addition tests.  Should the addition methods be derived automatically or do we have to add the new methods in `addition.jl` manually?
- I'm not sure if all calculations in `pdsparsemat.jl` are done in the most efficient way.

Sparse covariance matrices

---

src/PDMats.jl

In trying to use Distributions.jl on an HPC cluster, I found that I need to precompile each of my dependencies one-by-one. Adding this flag allowed me to force a precompile on PDMats.jl so that the subsequent precompiles actually ran inside the memory limit.

Added __precompile__ flag to help with using on small-memory VMs.

---

src/chol.jl

Ref JuliaLang/julia#13680
@andreasnoack

Fix chol depwarn

---

README.md
src/PDMats.jl
src/addition.jl
src/chol.jl
src/deprecates.jl
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
src/testutils.jl
src/utils.jl
test/addition.jl
test/pdmtypes.jl
test/runtests.jl

I've made PDMats typed on T<:AbstractFloat and removed all hard-coded references to Float64. 
It's all working cleanly for PDMat, PDDiagMat and ScalMat. A few workarounds of existing problems were needed to get it to work with PDSparseMat.
Reason why I did this is so that in the Distributions.jl package it will be easier to allow distributions to generate different floating types (for instance, the multi-variate normal function uses PDMat internally).
Can someone review and let me know if this is good to be merged into the main branch?

Supportfloat32

---

REQUIRE
src/PDMats.jl
src/utils.jl

For small to moderately sized covariance matrices, the time cost of allocating these views can be pretty big. This was also the only place this package used ArrayViews.

Rewrite colwise_dot! and colwise_sumsq! to use explict loops

---

src/PDMats.jl
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl

Relaxing the parameter type to `T <: Real` would allow PDMats (and thus eventually distributions using PDMats) to make use of automatic differentiation (à la ForwardDiff.jl).

generalize pdmats to work with ForwardDiff

---

src/PDMats.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/pdmtypes.jl

Now that element types of PDMats can vary, and we might want to promote element types for multiple parameters in Distributions, it would be handy to have PDMats take care of conversion between matrices with different element types.

added conversions between element types

---

src/generics.jl
src/scalmat.jl
src/testutils.jl
test/addition.jl
test/pdmtypes.jl

Nothing that should break anything

Various 0.6 fixes

---

src/pdiagmat.jl
src/pdmat.jl
src/scalmat.jl
test/pdmtypes.jl

These will be useful for getting `Distributions` running on 0.6 and they match what we define for arrays in Base.

Define AbstractArray{T} convert methods.

---

src/pdiagmat.jl
src/scalmat.jl
src/testutils.jl

Should help with https://github.com/JuliaStats/Distributions.jl/pull/594.

Widen (inv)quad(!) signatures to allow StridedArrays

---

.travis.yml
README.md
REQUIRE
src/PDMats.jl
src/addition.jl
src/chol.jl

Fixes #43. This will most likely also drop support for 0.4.

Only define methods for sparse matrices when CHOLMOD is available.

---

.gitignore
.travis.yml
README.md
REQUIRE
src/PDMats.jl
src/addition.jl
src/chol.jl
src/deprecates.jl
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
src/testutils.jl
src/utils.jl
test/addition.jl
test/generics.jl
test/pdmtypes.jl
test/runtests.jl

This is a work in progress on which I would appreciate comments.  I'm not sure what to do about sparse matrices.  At present in v0.7.0-DEV the CHOLMOD types and methods are in the SuiteSparse stdlib package but I don't know if they will stay there, because of the [L]GPL issues.  For the time being I have disabled the sparse parts.
As a parallel project I am working on switching the documentation to the Documenter package.  I see that a few vestiges have crept in here.
What I want to get done is

Changes for Julia v0.7

---

REQUIRE
src/generics.jl

Cut down on the noise when testing on v0.7

Use `Compat.undef` instead of `uninitialized`

---

REQUIRE
src/chol.jl
src/pdmat.jl
src/pdsparsemat.jl
src/testutils.jl
test/pdmtypes.jl

- Use `cholesky` in preference to `chol` or `cholfact`.
- Require version of Julia with that name
- Use accessor function to obtain `Q` from a `qr` decomposition.

Update to cholesky name and accessors

---

src/pdmat.jl
test/pdmtypes.jl

Fixes the problem with type stability of `whiten!` and `unwhiten!` which propagates, e.g. to multivariate random number generation in Distributions.jl.

Make whiten! and unwhiten! type stable

---

src/pdiagmat.jl

This PR removes the restriction on the `eltype`s of the inputs to the `PDiagMat` constructor. This allows conversion to take place inside with compatible types as opposed to just throwing an error. This was causing trouble in [Turing.jl](https://github.com/TuringLang/Turing.jl).

Remove input eltype restriction to inner constructor of PDiagMat

---

src/pdmat.jl

I relaxed some type constraints to partly enable the use of `Tracker.TrackedArray` with `Distributions.logpdf` and `Distributions.MvNormal`.
Relevant: https://github.com/TuringLang/Turing.jl/pull/743

Relax some strided vec or mat to abstract vec or mat

---

src/pdmat.jl

More stable versions of `quad` and `invquad` for the case of `(a::PDMat, x::AbstractVector)`.
This addresses issue #94 
`quad` uses the fact that: 
x'*a*x = x'*U'*U*x = (U*x)'*(U*x)
`invquad` uses the fact that:
x'*inv(a)*x = x'*inv(L*L')*x
= x'*inv(L')*inv(L)*x
= x'*inv(L)'*inv(L)*x
= (L \ x)'*(L \ x)

more stable quad and invquad with vectors

---

src/pdmat.jl
test/pdmtypes.jl

This PR adds a no-op `convert` method for when convert to an `AbstractArray`
with the same eltype as the PDMat.  This is a workaround to support things like
static arrays wrapped in PDMats.

Don't do anything if converting to AbstractArray with correct eltype

---

Project.toml

I'd like to get a release tagged with the changes from #101.  I've bumped the
patch version since AFAICT none of the changes since 0.9.7 are breaking (#95 and
#100 just provide more stable/efficient implementations of existing
functionality, although they may produce numerically different results, I'm not
sure).

Bump version for next release

---

src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
src/testutils.jl

Adds support for a `cholesky` accessor method where appropriate. Related to JuliaStats/Distributions.jl#731.
~~NOTE: Tests currently fail locally because of JuliaLinearAlgebra/Arpack.jl#12~~

cholesky accessor

---

src/PDMats.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl

Following issue #40 
Implemented `getindex` for all types for a nicer display of the PDMats

Making AbstractPDMat inherit from AbstractMatrix

---

.travis.yml
Project.toml
src/PDMats.jl
src/pdsparsemat.jl
test/pdmtypes.jl
test/runtests.jl
test/testutils.jl

stop depending on Arpack. The Arpack dependency sometimes causes some problems on some platforms and since Distributions depend on PDMats it means that most users end up depending on Arpack even though they never compute `eigmax` or `eigmin` of a sparse matrix even indirectly.

Remove eigmin and eigmax definitions for PDSparseMat and thereby

---

src/pdmat.jl
test/pdmtypes.jl

This addresses #98 where the original Matrix type (e.g., `Matrix{Int}`) can differ from the type returned by `Cholesky` (e.g., `Matrix{Float64}`). Therefore, we simply convert the Matrix type to the same paremetric types already converted by `Cholesky`.
Previously, this failed:
```julia
PDMat([1 0; 0 1])
```
This also addresses https://github.com/JuliaStats/Distributions.jl/issues/1004 (where my original problem started).

PDMat: convert Matrix type to the same Cholesky type

---

src/pdsparsemat.jl

Alter the inv() method for PDSparseMat to fall through to the inv() method of its underlying matrix.  If that is a SparseMatrixCSC, an error will be thrown asking the user to convert to a dense matrix first (the default behavior in LinearAlgebra).  This would address https://github.com/JuliaStats/PDMats.jl/issues/87.
I considered writing a more `PDMats`-specific error message (e.g. "ERROR: The inverse of a sparse matrix can often be dense and can cause the computer to run out of memory. If you are sure you have enough memory, please convert your matrix to a dense matrix, for instance using `inv(PDMat(Matrix(J)))`".  However, making the method fall through to whatever is defined for the underlying matrix type allows for the possibility someone will one day write a sparse matrix type that …

[Breaking] Make inverting a PDSparseMat throw an error

---

src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/addition.jl
test/testutils.jl

This PR fixes linear indexing of `PDiagMat` and `ScalMat`. Currently, for the last entry on the diagonal always `0` is returned since `d^2 % d == 0`. This also causes https://github.com/JuliaStats/PDMats.jl/issues/122.
I added some additional tests, both for indexing and for `mul!` (which probably should be implemented more efficiently though).
Fixes https://github.com/JuliaStats/PDMats.jl/issues/122.

Fix linear indexing of `PDiagMat` and `ScalMat`

---

src/pdiagmat.jl
test/kron.jl
test/pdmtypes.jl

Resolves #138.
~The `init` keyword argument to `sum` is only available from julia 1.6, so there's a fallback implementation for older versions.~
Edit: `init` keyword isn't type-stable, anyways, so dropping the version-branching.

Fix logdet(PDiagMat(zeros(0)))

---

src/chol.jl
src/deprecates.jl
src/pdmat.jl

See https://github.com/JuliaStats/PDMats.jl/pull/144#discussion_r742045912

deprecate CholType

---

README.md
src/PDMats.jl

It seems some functions (listed in `src/deprecates.jl`) were deprecated a long time ago but not removed. This PR removes them from the README and removes explicit exports of these functions such that `deprecates.jl` can be removed more easily in the next breaking release. For the time being, the functions are still exported by the `@deprecate` macro.

Clean exports

---

src/generics.jl
test/generics.jl
test/testutils.jl

This PR adds generic definitions of `LinearAlgebra.isposdef` and `LinearAlgebra.ishermitian`. It also removes `Base.eltype` and `Base.ndims` definitions which are not needed anymore since `AbstractPDMat{T} <: AbstractMatrix{T}`.
Fixes https://github.com/JuliaStats/PDMats.jl/issues/121. Fixes https://github.com/JuliaStats/PDMats.jl/issues/118.
I am not completely sure what's the best way to test these definitions (in particular `ishermitian`) - maybe I should add at least the failing examples for `isposdef`?

Add defaults for `isposdef` and `ishermitian`

---

src/chol.jl

Follow-up to https://github.com/JuliaStats/PDMats.jl/pull/144.
Should be possible to revert this once https://github.com/FluxML/Zygote.jl/pull/1114 has been resolved.

AD workaround

---

Project.toml
README.md
src/deprecates.jl
src/pdiagmat.jl
src/scalmat.jl
src/utils.jl
test/pdmtypes.jl

Alternative to https://github.com/JuliaStats/PDMats.jl/pull/141 that removes `inv_value` and `inv_diag` fields from `ScalMat` and `PDiagMat`.
Advantages compared with the current master branch are that there are no problems (incompatible types or undesired type promotions) with vectors and values where the inverse are of different type. Two helper functions are added that use division instead of operating with `inv(value)` directly to avoid undesired type promotions (e.g., if `x isa AbstractVector{Float32}` and `value isa Int`, then `inv(value) * x isa AbstractVector{Float64}` whereas `x / value isa AbstractVector{Float32}`).

Remove `inv_value` and `inv_diag`

---

Project.toml
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/pdmtypes.jl
test/testutils.jl

To simplify reviewing and to avoid unrelated changes, I extracted the fixes of right division and additional checks of dimensions from https://github.com/JuliaStats/PDMats.jl/pull/152.
This addresses the issues discussed in https://github.com/JuliaStats/PDMats.jl/pull/131#issuecomment-805893449 and makes the behaviour of `/` consistent with LinearAlgebra. Moreover, the dimension checks prevent incorrect behaviour, e.g., currently the following "works":
```julia
julia> using PDMats
julia> ScalMat(4, 2.0) * ones(3)
3-element Vector{Float64}:
2.0
2.0
2.0
julia> ScalMat(4, 2.0) * ones(3, 2)
3×2 Matrix{Float64}:
2.0  2.0
2.0  2.0
2.0  2.0
```

Fix right division and add checks of dimensions

---

Project.toml
src/chol.jl
test/chol.jl

This PR improves `chol_lower` and `chol_upper` by using the field `factors` directly:
```julia
julia> using PDMats, LinearAlgebra, BenchmarkTools
julia> C = cholesky(Symmetric(Matrix(I, 250, 250), :L));
julia> @btime PDMats.chol_lower($C);
julia> @btime PDMats.chol_upper($C);
julia> C = cholesky(Symmetric(Matrix(I, 250, 250), :U));
julia> @btime PDMats.chol_lower($C);
julia> @btime PDMats.chol_upper($C);
```

Improve  `chol_lower` and `chol_upper`

---

Project.toml
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/testutils.jl

Currently for `det(::AbstractPDMat)` the generic fallback in LinearAlgebra is used (https://github.com/JuliaLang/julia/blob/d4acead9130f97f0135bee604d94e1f67dabc70f/stdlib/LinearAlgebra/src/generic.jl#L1598-L1604) which performs an LU decomposition. This PR adds more efficient definitions for PDMat, PDSparseMat, ScalMat and PDiagMat.

Add definition of `det`

---

src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/kron.jl
test/runtests.jl
test/sqrt.jl
test/testutils.jl

The matrix square root, [`LinearAlgebra.sqrt()`](https://github.com/JuliaLang/julia/blob/dcc0efe26fd0490bf963be8d50dc6df83b91a868/stdlib/LinearAlgebra/src/dense.jl#L806), is not currently implemented for `PDMats`, i.e., `sqrt(::AbstractPDMat)` throws an error.
This PR implements this by applying `sqrt(Matrix(A))` in the generic case, `sqrt(A.mat)` where possible, plus specific cases for `PDiagMat`, `ScaleMat` and `PDSparseMat`.
Tests also written which check the specific cases return the same result as `sqrt(Matrix(A))`, which I believe is sufficient.

Implement matrix square root for PDMats

---

Project.toml
README.md
src/generics.jl
src/pdmat.jl
src/utils.jl
test/abstracttypes.jl
test/runtests.jl
test/testutils.jl

This is the partner to https://github.com/JuliaStats/Distributions.jl/pull/1552#issuecomment-1130483202
which will allow resolving https://github.com/JuliaStats/Distributions.jl/issues/1219
It doesn't go and implement everything falling back to AbstractArray,
just the operations required for Multivariate Normals,
and their family (so I can test them)
In some cases that implementation is just making the PDMat one generic, (since `cholesky(x::PDMat)=x.chol` is defined, etc.

Implement fallbacks for (un)whiten(!) and (inv)quad(!) to AbstractArray

---

Project.toml
src/pdmat.jl
test/pdmtypes.jl
test/specialarrays.jl

This PR fixes #155. This PR fixes #137.
```julia
julia> using PDMats, StaticArrays, BenchmarkTools, LinearAlgebra
julia> A = SMatrix{3,3}(rand(3, 3));
julia> B = A * A' +  I;
julia> @btime PDMat($(cholesky(B)));
45.653 ns (1 allocation: 128 bytes)
```
```julia
julia> using PDMats, StaticArrays, BenchmarkTools, LinearAlgebra
julia> A = SMatrix{3,3}(rand(3, 3));
julia> B = A * A' +  I;
julia> @btime PDMat($(cholesky(B)));
9.706 ns (0 allocations: 0 bytes)
```

Improve constructor `PDMat(::Cholesky)`

---

Project.toml
src/pdiagmat.jl
test/kron.jl
test/specialarrays.jl

This PR simplifies `kron` with `PDiagMat` and also avoids indexing issues (see #163).
```julia
julia> using PDMats, BenchmarkTools
julia> A = PDiagMat(rand(100));
julia> B = PDiagMat(rand(100));
julia> @btime kron($A, $B);
13.395 μs (103 allocations: 166.55 KiB)
```
```julia
julia> using PDMats, BenchmarkTools
julia> A = PDiagMat(rand(100));
julia> B = PDiagMat(rand(100));
julia> @btime kron($A, $B);
4.625 μs (6 allocations: 78.34 KiB)
```
Accidentally, I had pushed the changes directly to the master branch (already reverted it).
Edit: Additionally, the PR fixes some type inference issues:
```julia
julia> using PDMats, StaticArrays, Test
julia> typeof(kron(PDiagMat(@SVector([0.1, 0.2, 0.5])), PDiagMat(@SVector([0.2, 0.4, 1.2]))))
PDiagMat{Float64, SVector{9, Float64}}
julia> …
```

Simplify `kron(::PDiagMat, ::PDiagMat)`

---

Project.toml
README.md
src/addition.jl
src/deprecates.jl
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/pdmtypes.jl
test/testutils.jl

This PR implements the suggestion in https://github.com/JuliaStats/PDMats.jl/issues/169#issuecomment-1166260830 and deprecates `dim` in favour of `LinearAlgebra.checksquare`.
Fixes #169.

Deprecate `dim`

---

src/scalmat.jl

It seems one use of `dim` was not removed from the package when it was deprecated.

dim(a) -> LinearAlgebra.checksquare(a)

---

src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
test/pdmtypes.jl
test/testutils.jl

This PR adds `AbstractPDMat(::AbstractMatrix)`, `AbstractPDMat(::Cholesky)` and `AbstractPDMat(::CholTypeSparse)`.
The main motivation is that this allows to specialize on the matrix type, which allows downstream packages such as Distributions (e.g. in https://github.com/JuliaStats/Distributions.jl/blob/9f9c5caf6cd99c5205a11ca1c8d6b6471fc9ce29/src/multivariate/mvnormal.jl#L201-L203) to just use `AbstractPDMat(A)` instead of adding custom dispatches.
Unfortunately, we can't add something like `AbstractPDMat(A::UniformScaling)` (size unknown) or `AbstractPDMat(A::Diagonal{<:Real,<:FillArrays.Fill{<:Real}})` (FillArrays dependency).
Fixes #136 (without lying about the return type).

Add `AbstractPDMat` constructor

---

Project.toml
src/pdiagmat.jl
src/pdmat.jl
src/scalmat.jl
test/pdmtypes.jl
test/specialarrays.jl

As the title says, this PR fixes tests on all Julia versions.
The main problem on the master branch is that the return type of `/(::AbstractVector, ::AbstractPDMat)` is not consistent anymore with the behaviour in LinearAlgebra >= 1.9. I was not able to track down the exact commit where this behaviour changed but since the first alpha release of 1.9 LinearAlgebra returns a vector in these cases whereas in Julia <= 1.8.5 a matrix was returned.
The second problem were the BandedMatrices tests; they were failing due to some upstream problems (only the computations of the reference values were affected it seems) but this could be fixed by simplifying the calculation of the ground truth values.

Fix `/` on Julia >= 1.9 and broken tests

---

Project.toml
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/pdmtypes.jl

Adds missing `convert` definitions and improves efficiency of existing ones. For instance, the PR fixes unnecessary calls of `cholesky` when converting `PDMat`s.
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1781.
Edit: #180 should be merged first.

Improve `convert` definitions

---

Project.toml
src/scalmat.jl
test/specialarrays.jl

Currently, `ScalMat` does not support `X_A_Xt` etc. with static arrays. For instance, running the tests in this PR on the master branch yields
```julia
StaticArrays: Error During Test at REPL[10]:42
Test threw exception
Expression: X_A_Xt(A, X) isa SMatrix{10, 10, Float64}
setindex!(::SMatrix{10, 10, Float64, 100}, value, ::Int) is not defined.
Hint: Use `MArray` or `SizedArray` to create a mutable static array
...
StaticArrays: Error During Test at REPL[10]:43
Test threw exception
Expression: X_A_Xt(A, X) ≈ Matrix(X) * Matrix(A) * (Matrix(X))'
setindex!(::SMatrix{10, 10, Float64, 100}, value, ::Int) is not defined.
Hint: Use `MArray` or `SizedArray` to create a mutable static array
...
StaticArrays: Error During Test at REPL[10]:45
Test threw exception
Expression: X_invA_Xt(A, X) isa …
```

Support StaticArrays in X(t)_(inv)A_X(t) with ScalMat

---

Project.toml
src/pdiagmat.jl
src/scalmat.jl
test/testutils.jl

We don't have to go through `cholesky(::Diagonal)` in LinearAlgebra (e.g. https://github.com/JuliaLang/julia/blob/28d9f730c1927297fc0cfc415c842968aa1a3a71/stdlib/LinearAlgebra/src/diagonal.jl#L868) when computing `cholesky(::ScalMat)` or `cholesky(::PDiagMat)` but we can construct the `Cholesky` object directly without any intermediate steps.
This improves performance significantly:
```julia
julia> using PDMats, BenchmarkTools, LinearAlgebra
julia> A = ScalMat(10, 3.2);
julia> @btime cholesky($A);
47.733 ns (2 allocations: 288 bytes)
julia> A = ScalMat(100, 3.2);
julia> @btime cholesky($A);
160.778 ns (2 allocations: 1.75 KiB)
julia> A = ScalMat(1_000, 3.2);
julia> @btime cholesky($A);
1.458 μs (2 allocations: 15.88 KiB)
julia> A = PDiagMat(fill(3.2, 10));
julia> @btime cholesky($A); …
```

Simplify `cholesky` for `ScalMat` and `PDiagMat`

---

src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl

In the `convert` methods for `PDMat`, `PDDiagMat`, and `PDSparseMat` we call the inner constructors that were deprecated in #178. This PR fixes all calls of such deprecated constructors (can be seen e.g. in the output when running tests on Julia 1.0 and also checked with ripgrep).

Fix calls of deprecated constructors

---

Project.toml
src/generics.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/specialarrays.jl

Based on #181, this PR also adds support for `whiten`, `unwhiten`, `quad`, and `invquad` with static arrays.
The PR grew a bit larger, hence I kept it separate from #181 for now.
Main points:
- Do not use mutation in non-mutating methods (in a few cases, allocations could be reduced by specializing on `Array`, see my comment in #181 - should we do this?)
- Improve composability by forwarding calls with generic matrices to `f(..., AbstractPDMat(x), ...)` (as a nice side effect, this means that more efficient implementations are called automatically whenever `AbstractPDMat(x)` is specialized; this is the case, e.g., for `Diagonal` matrices).
- Check dimensions.

Support `(un)whiten` and `(inv)quad` with static arrays

---

Project.toml
src/pdiagmat.jl

This PR removes the `sqrt` computations and `permutedims` calls from the tri product implementations for `PDiagMat`.
```julia
julia> using PDMats, BenchmarkTools
julia> a = PDiagMat(rand(10)); X = randn(10, 10);
julia> @btime Xt_A_X(a, X);
366.343 ns (2 allocations: 1.75 KiB)
julia> @btime X_A_Xt(a, X);
377.044 ns (4 allocations: 1.84 KiB)
julia> @btime Xt_invA_X(a, X);
394.279 ns (2 allocations: 1.75 KiB)
julia> @btime X_invA_Xt(a, X);
404.580 ns (4 allocations: 1.84 KiB)
julia> a = PDiagMat(rand(100)); X = randn(100, 100);
julia> @btime Xt_A_X(a, X);
48.125 μs (4 allocations: 156.34 KiB)
julia> @btime X_A_Xt(a, X);
46.333 μs (6 allocations: 156.44 KiB)
julia> @btime Xt_invA_X(a, X);
52.667 μs (4 allocations: 156.34 KiB)
julia> @btime X_invA_Xt(a, X);
49.166 μs (6 allocations: 156.44 …
```

Improve performance of tri products for `PDiagMat`

---

src/PDMats.jl
src/chol.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/specialarrays.jl
test/testutils.jl

PDMats 0.11.26 broke `invquads!` due to a bug in the check of the dimensions of the input arguments: https://github.com/JuliaStats/Distributions.jl/issues/1789
This issues was not noticed since `quad!` and `invquad!` were not tested.

Fix and test broken `quad!` and `invquad!`

---

src/chol.jl
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
test/specialarrays.jl
test/testutils.jl

The performance improvement in https://github.com/JuliaStats/PDMats.jl/commit/a97533d1b2c162d6354834be774beff769f7e8eb had an unforeseen side effect: It increases the probability that the output of the tri products (for `PDiagMat` matrices) is numerically not exactly symmetric. This causes downstream issues (e.g., in Distributions: https://github.com/JuliaStats/Distributions.jl/issues/1789#issuecomment-1765302266) in further computations (such as `cholesky`) that fail/error (more often) if the output is not symmetric.
This PR wraps the output of `X_A_Xt` etc. in a `Symmetric` to fix these issues. I also added tests.

Ensure that the output of `X_A_Xt` etc. is symmetric

---

test/chol.jl

With the modification in this PR it should be much less likely to see random test failures such as https://github.com/JuliaStats/PDMats.jl/actions/runs/6544749785/job/17771846929#step:6:172.

Reduce probability of test failures

---

Project.toml
src/pdiagmat.jl
src/pdmat.jl
test/pdmtypes.jl
test/specialarrays.jl

Implements `Base.broadcastable` for `PDMat` and `PDiagMat` by falling back to the wrapped matrix and a `Diagonal` object, respectively. Many generic fallbacks use broadcasting, and by falling back on the underlying better supported `AbstractMatrix` objects we reduce the number of surprising and undesired results in broadcasting operations but also e.g. subtraction (see https://github.com/JuliaStats/PDMats.jl/issues/195#issuecomment-1809816905).
One could similarly define `Base.broadcastable(a::ScalMat) = Base.broadcastable(Diagonal(fill(a.value, a.dim)))` but this leads to undesired results when working with e.g. static arrays (and causes undesired allocations which could maybe be fixed by working with FillArrays.Fill - but only recently we noticed that a dependency on FillArrays would …

Improve broadcasting of `PDMat` and `PDiagMat`

---

src/pdmat.jl

```julia
julia> X = randn(400,600); A = X * X' + I; isposdef(A)
true
julia> S = Symmetric(A);
julia> P = PDMat(S, cholesky(S));
julia> @btime eigmax($P);
7.598 ms (11 allocations: 1.36 MiB) # master
4.388 ms (11 allocations: 1.36 MiB) # PR
```

Wrap parent of `PDMat` in `Symmetric` in `eigmin`/`eigmax`

---

.gitignore

Julia v1.11 allows manifest files with the version in the filename, and we may ignore these as well.

Add versioned manifest file to gitignore

---

.github/dependabot.yml
.github/workflows/IntegrationTest.yml
.github/workflows/ci.yml
Project.toml
src/pdiagmat.jl
src/pdmat.jl
src/pdsparsemat.jl
src/scalmat.jl
src/utils.jl
test/pdmtypes.jl
test/specialarrays.jl
test/testutils.jl

In https://github.com/JuliaStats/PDMats.jl/pull/212, it was proposed to update the Julia compat to 1.10. I opened a separate PR for this move since there are quite many `VERSION` checks that we could (and should) get rid of in this update but these changes are really unrelated to #212 otherwise.
I used the opportunity to update the CI setup, and in particular add tests with `min`, `lts` and `pre`.

Update Julia compat to 1.10 and update CI setup

---

Project.toml
src/chol.jl
src/pdmat.jl
test/pdmtypes.jl
test/specialarrays.jl

This allows one to convert both the eltype and matrix type. In practice, my main use for this is to  support generic programming with both `Matrix` and `StaticArrays.SMatrix`.
Perhaps the only potentially-controversial aspect is moving the dimensionality check into the inner constructor. If we want to make it impossible to construct an inconsistent `PDMat`, that's where it has to be.

More conversion in `PDMat`

---

Project.toml
src/scalmat.jl
test/pdmtypes.jl

Fixes https://github.com/JuliaStats/PDMats.jl/issues/211.

Fix `convert` for `ScalMat`
